### ISSUE TITLE
Allow to implement nominations without implementing LAs

### ISSUE THREAD

**Issue by pleys** [erasmus-without-paper/ewp-wp4-use-cases#3]
If I understand correct both nominations and learning agreement are part of the Outgoing Mobilties API. Is it possible to only implement the nominations functionality of this API? I am asking this because a lot of institutions don't handle the learning agreement within their SIS or mobility software.

**Comment by wrygiel** [comment]
In our current model it would be required to implement either both or none - it is not possible to implement just the nominations, without handling LAs.

Solutions:
1. Such institutions would need to stick with their legacy mobility software in this case, and switch to EWP only after they become interested in handling LAs.
2. We could think of supporting this natively, but we would need to split our APIs even further. Both nominations and LAs would require a separate `<timeline>` in this case, which would make it even more complicated.

I would go for solution 1 unless there is a strong need for solution 2. I think @erasmus-without-paper/wp2 might answer this.

@erasmus-without-paper/wp3 might have some more thoughts on this.

@erasmus-without-paper/all-members

**Comment by janinamincer-daszkiewicz** [comment]
Nominations are easier to implement. It might be a good option to allow institutions start with nominations and after some time add implementation of LAs.

**Comment by pleys** [comment]
I would strongly advise to come with a solution where an institution can implement only nominations. Nominations is a more straightforward process and some institutions might indeed (as @janinamincer-daszkiewicz comments above) prefer to start with implementing nominations (and will maybe never implement LAs).

@StefanJahnke what are your thoughts about this issue?

**Comment by StefanJahnke** [comment]
Hello,
I strongly advise for having separate processes as well, as suggested in my use-cases. Excluding institutions right from the start because they handle those decentralised and independent from each other would harm the EWP Network. 

The suggestion by @wrygiel to wait till they "want to also handle the LAs" is unrealistic. Changing such procedures is in most institutions unfortunately not the choice of a single person but has political implications.

If you deem adapting the current architecture as too complicated, wouldn't it be easier to think about a different architectural approach to how 'mobilities' are handled?

**Comment by wrygiel** [comment]
Okay then! We will split the Mobilities API into two separate APIs. Let me think about this for some time. There are many ways of achieving this, I'll try to find the best one.

**Comment by wrygiel** [comment]
Please review the attached commits (especially [the first one](https://github.com/erasmus-without-paper/ewp-specs-api-mobility-update/commit/7f34c49e176f6c0477c0579f74073ef22b0b3651)). I believe this solves the issue?
